[meta title:"Finreg Hub" description:"Short description of your project" /]

[Header
  title:"Finreg Hub"
  subtitle:""
  author:"John Rieth"
  authorLink:"https://github.com/johnrieth" /]

# Capital & Liquidity

Capital requirements have been implemented to ensure financial institutions survive losses and declines in asset values. 

## Think Tanks/Academia on Capital Requirements
  - [link text: "NYU Stern: Bank Capital Regulation and the Off-Ramp" href:"http://www.stern.nyu.edu/sites/default/files/assets/documents/Bank%20Capital%20Regulation%20and%20the%20Off-Ramp.pdf"/]

  - [link text:"Brookings: Higher capital is not a substitute for stress tests" href:"https://www.brookings.edu/research/higher-capital-is-not-a-substitute-for-stress-tests/"/]
  
  - [link text: "Why Banking Leverage Are Not Enough" href:"http://rooseveltinstitute.org/why_we_need_both_capital_requirements/"/]
  
  - [link text: "How Bank Regulations Hinder the U.S. Recovery" href:"https://www.cato.org/publications/commentary/how-bank-regulations-hinder-us-recovery"/]

# Financial Stability Oversight Council (FSOC)

The FSOC role is to identify and respond to financial stability threats.  


### Bibliography

[link text:"Capital Guidelines and Adequacy" href:"https://www.federalreserve.gov/supervisionreg/topics/capital.htm"/]